version: "3.3"
services:
  postgres:
    container_name: app_comic_db
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345
    restart: always
  app:
    container_name: app_rails
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 4000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - postgres